/// Status of an application during its lifecycle.
enum ApplicationStatus {
  queued,
  processing,
  completed,
  failed,
  exported;

  String get displayName {
    switch (this) {
      case ApplicationStatus.queued:
        return 'Wartend';
      case ApplicationStatus.processing:
        return 'In Bearbeitung';
      case ApplicationStatus.completed:
        return 'Abgeschlossen';
      case ApplicationStatus.failed:
        return 'Fehlgeschlagen';
      case ApplicationStatus.exported:
        return 'Exportiert';
    }
  }
}

/// Represents a single job application generated by the system.
class Application {
  final int id;
  final String jobTitle;
  final String company;
  final String jobUrl;
  final ApplicationStatus status;
  final String? pdfPath;
  final String? errorMessage;
  final DateTime createdAt;
  final DateTime? completedAt;

  const Application({
    required this.id,
    required this.jobTitle,
    required this.company,
    required this.jobUrl,
    this.status = ApplicationStatus.queued,
    this.pdfPath,
    this.errorMessage,
    required this.createdAt,
    this.completedAt,
  });

  Application copyWith({
    int? id,
    String? jobTitle,
    String? company,
    String? jobUrl,
    ApplicationStatus? status,
    String? pdfPath,
    String? errorMessage,
    DateTime? createdAt,
    DateTime? completedAt,
  }) {
    return Application(
      id: id ?? this.id,
      jobTitle: jobTitle ?? this.jobTitle,
      company: company ?? this.company,
      jobUrl: jobUrl ?? this.jobUrl,
      status: status ?? this.status,
      pdfPath: pdfPath ?? this.pdfPath,
      errorMessage: errorMessage ?? this.errorMessage,
      createdAt: createdAt ?? this.createdAt,
      completedAt: completedAt ?? this.completedAt,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'jobTitle': jobTitle,
        'company': company,
        'jobUrl': jobUrl,
        'status': status.name,
        'pdfPath': pdfPath,
        'errorMessage': errorMessage,
        'createdAt': createdAt.toIso8601String(),
        'completedAt': completedAt?.toIso8601String(),
      };

  factory Application.fromJson(Map<String, dynamic> json) => Application(
        id: json['id'] as int,
        jobTitle: json['jobTitle'] as String,
        company: json['company'] as String,
        jobUrl: json['jobUrl'] as String,
        status: ApplicationStatus.values.firstWhere(
          (e) => e.name == json['status'],
          orElse: () => ApplicationStatus.queued,
        ),
        pdfPath: json['pdfPath'] as String?,
        errorMessage: json['errorMessage'] as String?,
        createdAt: DateTime.parse(json['createdAt'] as String),
        completedAt: json['completedAt'] != null
            ? DateTime.parse(json['completedAt'] as String)
            : null,
      );
}